### ISSUE TITLE
consider making vega depend on vega-lib

### ISSUE THREAD

**Issue by tvald** [vega/vega-lib#1]
Not sure whether this repo or vega/vega is the right place for this discussion.

Following from [vega/vega-tooltip#165](https://github.com/vega/vega-tooltip/issues/165), it's difficult for downstream libraries and add-ons to support both `vega` and `vega-lib`, since `npm` doesn't support [alternative dependencies](https://wiki.debian.org/DependencyHell#Dependency_alternatives).

In the particular case of `vega-tooltip`, I think they can get away with avoiding an explicit reference to either `vega` or `vega-lib`, which would permit the consuming project to choose either.

In the more general case, making `vega` depend on `vega-lib` would allow downstream libraries and add-ons to explicitly depend on `vega-lib`, while consuming projects could still depend on all of `vega` if necessary.

**Comment by tvald** [comment]
This also follows from the original issue that led to `vega-lib`:

[vega/vega#1073](https://github.com/vega/vega/issues/1073#issuecomment-366813633)
> nyurik:
> Should vega depend on vega-lib to minimize potential build / code synchronization issues?

[vega/vega#1073](https://github.com/vega/vega/issues/1073#issuecomment-366814936)
> jheer:
> My original thinking was "yes", but then I changed my mind when I went to implement this. For the time being I found it more convenient to manage all the example specs (including those in both tests and documentation) from a single repo (Vega), test them all together prior to release, then release vega-lib in parallel. I'm open to revisiting this later on, though.

**Comment by domoritz** [comment]
Having two libraries that can be used interchangeably (e.g. in embed) confuses build systems and makes it tricky to set up typescript (e.g. this caused some trouble for a jupyterlab release). I think it would be nice to use vega-lib in vega.

**Comment by tvald** [comment]
> I think it would be nice to use vega-lib in vega.

That would definitely be ideal. I don't know if @jheer has any further thoughts on this since creating vega-lib.

**Comment by domoritz** [comment]
I think I was able to resolve most typescript errors with https://github.com/vega/vega-lib/pull/3. 

One thing I'm worried about is if a project depends on both Vega and Vega-lib, do we double the code? Probably not double because Vega itself consists of many libraries.

**Comment by nyurik** [comment]
If project depends on both vega & vega-lib,  and vega (properly) depends on vega-lib, there shouldn't be any code increase.  I am guessing you mean a scenario when A depends on B and C;  B depends on vega, C depends on vega-lib.   In case vega does not depend on vega-lib, it should also be okayish, since most of the code is in dependencies anyway, and they are simply organizational shells.

**Comment by jheer** [comment]
As of version 4.0.0-rc.1, vega now depends on vega-lib. As a result, vega-lib now also houses the general Vega test suite, build scripts, and continuous integration setup.

**Comment by domoritz** [comment]
@jheer Fantastic! we still need to use Vega in the editor because of the examples. I wonder whether we could move them out of the Vega repo so that we don't need to compile canvas in the editor.
