### ISSUE TITLE
vega-lib has no tagged commits/releases

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lib#22]
Do we want to have tagged commits for consistency or is this going away with a monorepo anyway?

**Comment by sebastibe** [comment]
I don't know / think it is related but I have the following issue since v4.4.0: I can't seem to be able to install any other versions than the 4.4.0:
```
npm i vega-lib@^4.3.0
+ vega-lib@4.4.0
```

Could it be an issue with the last publication?
